### PR TITLE
Add support for CompletionItem.command

### PR DESCRIPTION
**Pull request by nwolverson**
Maybe controversial smuggling extra data around with the completion item, which we get returned to us in `onDidInsertSuggestion`. Maybe there's a better way, also I have never used flow so this is probably not ideal.

I think the same strategy as for `command` can be used for additional text edits - i.e. on the didInsert callback the additional edits can be retrieved and applied to the document.

#114

### CODE REVIEW

**Comment by damieng** [comment]
I like the idea of providers being able to provide their own OnDidInsertSuggestion that gets returned as part of it and we could include a command binder - I think though that the two should be up to the ide-x author to wire up unless there's a precedence somewhere?

**Comment by nwolverson** [comment]
My thinking was that a CodeAction specifies a `command` which is wired up to execute a command on the server automatically https://github.com/atom/atom-languageclient/blob/5e1d6641d2e53b6334208c1efed5be2e94412d21/lib/adapters/code-action-adapter.js#L60 and similarly CompletionItem has a `command`.

But certainly (in both cases) I could see that might not be what you want. I think eg in VSCode the command is automatically executed on the client side but those commands are then forwarded to the server.

I'm not sure I follow what you are suggesting particularly "command binder" - there is some `AutoLanguageClient.onDidInsertSuggestion` which can be overridden and gets given the `command` (or even the original CompletionItem)?

**Comment by nwolverson** [comment]
@damieng is this closer to what you were suggesting? Expose `onDidInsertSuggestion` to be overridden, passing the original completion item entirely, as well as the autocomplete+`onDidInsertSuggestion` argument, making it easy to wire up command etc.

**Comment by damieng** [comment]
Here's my revised idea - basically just implementing the onDidInsertSuggestion hook - used in conjunction with the new conversion hook api this should give you the flexibility to store and re-obtain the original completion item etc.  

Will merge today unless there are objections.

**Comment by nwolverson** [comment]
Sorry I wasn't able to get back to this, thanks for making those changes - looks good to me.

**Comment by damieng** [comment]
No problem - glad we found a solution that works.

**Pull request merged**
