### PR TITLE
use rimraf

### LINKED ISSUE #275: Doesn't install on windows
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

Won't install on windows. 

`'rm' is not recognized as an internal or external command`

`npm run clean` runs `rm -rf build`

related https://github.com/Gert-dev/php-ide-serenata/issues/477

### Steps to Reproduce

1. run `npm i` on windows

**Expected behavior:**

installs

**Actual behavior:**

errors

**Reproduces how often:**

100%

### PR DESCRIPTION
**Pull request by UziTech**
### Identify the Bug

Doesn't install on window

fixes #275 

### Description of the Change

use `rimraf` instead of `rm -rf`

### Possible Drawbacks

none

### Verification Process

installed on windows

### Release Notes

Fix windows install

### CODE REVIEW

**Comment by Gert-dev** [comment]
This makes me curious, do other language clients work on Windows at all? It seems highly unlikely that we're the first to encounter this error as there have been many language clients for much longer. 

php-ide-serenata has only just switched and Windows users now immediately encounter this error.

**Comment by UziTech** [comment]
It also seems fairly strange that tests pass on [appveyor](https://ci.appveyor.com/project/Atom/atom-languageclient/branch/master)

**Comment by Gert-dev** [comment]
Hmm, I think I see what the problem is (#166), it is because Serenata is using an unstable version of the atom-languageclient - intentionally, I might add, since I need the targeted commit to fix an issue with autocompletion.

It is likely it'll be solved by targeting a stable release, but autocompletion will be bugged for users. If a new stable release is performed here, that would likely also fix the problem (but this fix might as well).

**Comment by UziTech** [comment]
@Aerijo @50Wliu @damieng @atom Any feedback?

**Comment by damieng** [comment]
I haven't worked on Atom or the language client in well over a year, sorry.

**Comment by UziTech** [comment]
@atom Could we get this merged so it works on windows and a new release?

**Pull request closed without merging**
